spring.application.name=sias

spring.datasource.url=jdbc:postgresql://localhost:5432/system
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e3a3891f177288
spring.mail.password=b0530c0b13e9cd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true