package com.system.sias.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;

@Entity
@Table(name = "admissions")
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor
public class Admission {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Step 1: Personal Data
    private String firstName;
    private String lastName;
    private String middleName;
    private String nameExtension;
    private LocalDate dateOfBirth;
    private String sex;
    private String birthPlace;
    private String civilStatus;
    private String nationality;
    private String religion;
    private String contactNumber;
    private String email;
    private String height;
    private String weight;


    // Step 2: Family Background
    private String fatherName;
    private String fatherOccupation;
    private String motherName;
    private String motherOccupation;
    private String guardianName;
    private String emergencyContact;
    private String fatherMobile;
    private String fatherIncome;
    private String motherMobile;
    private String motherIncome;

    // Step 3: Admission Data
    private String admissionType; // e.g., Freshman, Transferee
    private String program;       // The Course applied for
    private String department;    // The College/Dept
    private String yearLevel;
    private String lastSchoolAttended;
    private String lrn;           // Learner Reference Number
    private Double gwa;           // Grade Point Average

    // Home Address
    private String homeCountry;
    private String homeRegion;
    private String homeProvince;
    private String homeMunicipality;
    private String homeBarangay;
    private String homeStreet;



    // System Fields
    private String controlNumber; // Generated by script.js
    private String status;        // PENDING, APPROVED, REJECTED
    private LocalDate applicationDate = LocalDate.now();

    @OneToOne
    @JoinColumn(name = "student_account_id")
    private Student student; // Linked after approval
}