spring.application.name=sias-admission-system
spring.datasource.url=jdbc:postgresql://localhost:5432/mainDB
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.date-format=yyyy-MM-dd
spring.jpa.open-in-view=false
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true