spring.application.name=sias

spring.datasource.url=jdbc:postgresql://localhost:5432/system
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
